#!/usr/bin/env python
# -*- coding: utf-8 -*-
try:
    os
except:
    import os
import sys, commands, optparse
def __main__():
    parser = optparse.OptionParser()
    parser.add_option('-s', '--signal', action='store', dest='signal', default=15, help='signal')
    (options, args) = parser.parse_args(sys.argv)    
    grep_list = ['py']
    cmd = 'ps ax'
    for g in grep_list:
        cmd += '|grep %s' % g
    res = commands.getoutput(cmd)
    process = {}
    for line in res.split('\n'):
        for jobname in line.split()[4:]:
            if '8000' in jobname:
                cmd = 'sudo kill -%s %s' % (options.signal, line.split()[0])
                print cmd[5:]
                os.system(cmd)
__main__()



