#!/usr/bin/python
import sys, os
#import commands
import random


album_path = sys.argv[1] 
print album_path

files = os.listdir(album_path)
#random.shuffle(files)
album, ext = os.path.split(album_path)
base, album = os.path.split(album)
print '[31m%s[m' % album
for file in files:
    print '[31m%s[m' % file
for file in files:
    file_path = os.path.join(album_path, file)
    print 'now playing [31m%s[m' % file
    os.system('echo "afplay - now playing %s" | growlnotify' % file)
    os.system('afplay -v .2 -q 1 "%s"' % file_path)

